### ISSUE TITLE
Does gpkit work with python3?

### ISSUE THREAD

**Issue by vanhecke1** [convexengineering/gpkit#1039]
Hi,

When I tried to setup gpkit with python3, it didnt work out.

Particularly, the commands "pip install ctypesgen --pre" and "pip install gpkit" does not work for my Ubuntu 16.04 pc. You can find the error messages in below.

Thanks a lot!

```
Error message for "pip install ctypesgen --pre"
Collecting ctypesgen
  Using cached ctypesgen-0.r125.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0teb07md/ctypesgen/setup.py", line 13, in <module>
        import ctypesgencore
      File "/tmp/pip-build-0teb07md/ctypesgen/ctypesgencore/__init__.py", line 56, in <module>
        import processor
    ImportError: No module named 'processor'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0teb07md/ctypesgen/

Error message for "pip install gpkit"



Collecting gpkit
  Using cached gpkit-0.5.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5gnqcug8/gpkit/setup.py", line 8, in <module>
        from gpkit.build import build_gpkit
      File "/tmp/pip-build-5gnqcug8/gpkit/gpkit/__init__.py", line 117, in <module>
        enable_units()
      File "/tmp/pip-build-5gnqcug8/gpkit/gpkit/__init__.py", line 71, in enable_units
        units = GPkitUnits()
      File "/tmp/pip-build-5gnqcug8/gpkit/gpkit/__init__.py", line 36, in __init__
        if hasattr(ureg, "__nonzero__"):
      File "/home/lmc3696/myvirtualenv/lib/python3.5/site-packages/pint/unit.py", line 375, in __getattr__
        return self.Unit(item)
      File "/home/lmc3696/myvirtualenv/lib/python3.5/site-packages/pint/unit.py", line 66, in __new__
        inst._units = inst._REGISTRY.parse_units(units)._units
      File "/home/lmc3696/myvirtualenv/lib/python3.5/site-packages/pint/unit.py", line 1201, in parse_units
        units = self._parse_units(input_string, as_delta)
      File "/home/lmc3696/myvirtualenv/lib/python3.5/site-packages/pint/unit.py", line 1223, in _parse_units
        cname = self.get_name(name)
      File "/home/lmc3696/myvirtualenv/lib/python3.5/site-packages/pint/unit.py", line 753, in get_name
        raise UndefinedUnitError(name_or_alias)
    pint.errors.UndefinedUnitError: '__nonzero__' is not defined in the unit registry
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5gnqcug8/gpkit/
```

**Comment by bqpd** [comment]
GPkit doesn't currently support Python3 (it did in the past for antimony CAD, which is no longer maintained)...but now we know people want it, I'll fix that and add some tests!

(out of curiosity, what's your use case for GPkit?)

**Comment by vanhecke1** [comment]
I see, thanks for quick response!

I would like to use GPkit for a research project.

**Comment by bqpd** [comment]
I guess I'm more wondering if you'll be using SPs / GPs and using math models or representing engineering equations (with units and so on). :) The development pattern for GPkit is all about "paving the cowpaths": that is making sure our abstractions match how users think of their models so their code can be conceptually clean and we can make nice generalized [visualizations](http://gpkit.readthedocs.io/en/latest/visint.html).

**Comment by vanhecke1** [comment]
I will be using GP's to generate math model, actually I used GPkit in python2 a bit but I needed GPkit in python3. I will figure out a way to use GPkit somehow. :)

Thanks for your response!
