### ISSUE TITLE
solution.append error while relaxed solving SP sweeps

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1258]
Concerns commit ea96f9c31 in SPaircraft/gpkitIssue branch. 
The relaxed_constants algorithm works until the final solve, but the solution dict generation breaks at the very end. I run this:
```python
run SP_aircraft.py
sol = run_optimal_737('W_{f_{total}}',True,False,True)
```
Where optimal_737 has a swept variable with two values. And I get the following error:
```python
Traceback (most recent call last):
  File "C:\Users\Berk\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-25b05881a1f3>", line 1, in <module>
    sol = run_optimal_737('W_{f_{total}}',True,False,True)
  File "C:\Users\Berk\Dropbox (MIT)\MIT Graduate School\Code\SPaircraft\SP_aircraft.py", line 380, in run_optimal_737
    sol = m_relax.localsolve(verbosity=1, iteration_limit=200, reltol=0.01, mutategp=mutategparg)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\prog_factories.py", line 77, in solvefn
    solver, verbosity, *args, **kwargs)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\constraints\prog_factories.py", line 132, in run_sweep
    solution.append(result)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\small_classes.py", line 102, in append
    _append_dict(sol, self)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\small_classes.py", line 142, in _append_dict
    d_out[k] = _append_dict(v, d_out[k])
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\small_classes.py", line 142, in _append_dict
    d_out[k] = _append_dict(v, d_out[k])
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\small_classes.py", line 145, in _append_dict
    d_out[k].append(v)
  File "c:\users\berk\dropbox (mit)\mit graduate school\code\gpkit\gpkit\keydict.py", line 139, in __getitem__
    raise KeyError(key)
KeyError: f_{eadd}_Mission/Aircraft/Relax
```
I get a different key for the KeyError statement at the end in different attempts, which suggests that the issue is in the dict build-up. Lmk if you have any ideas.

**Comment by bqpd** [comment]
Works on current master...
