### ISSUE TITLE
Boundedness warnings are becoming problematic.

### ISSUE THREAD

**Issue by 1ozturkbe** [convexengineering/gpkit#1435]
@bqpd I think there is something wrong with the boundedness warnings. 
I'm solving basic GPs to calculate probability of failure for robust. The same GP, which I know for a fact is bounded and I have solved about a thousand times, has now started producing errors. 
Check out the testing for commit ede335a, branch tidy of robust. The tests pass on Windows machines, and fail on the others, because of:
```python
Traceback (most recent call last):
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/robust/testing/t_primitives.py", line 56, in test_methods
    _ = rm.robustsolve(verbosity=0)
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/robust/robust.py", line 235, in robustsolve
    self.setup(verbosity, **options)
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/robust/robust.py", line 207, in setup
    feasible=True)
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/robust/robust.py", line 417, in find_number_of_piece_wise_linearization
    sol_upper = RobustModel.internalsolve(model_upper, verbosity=0)
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/robust/robust.py", line 454, in internalsolve
    return model.solve(verbosity=verbosity)
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/gpkit/gpkit/constraints/prog_factories.py", line 123, in solvefn
    self.program, progsolve = genfunction(self)
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/gpkit/gpkit/constraints/prog_factories.py", line 80, in programify
    prog = program(self.cost, self, constants, **kwargs)
  File "/Users/jenkins/workspace/robust_PullRequest/mosek/gpkit/gpkit/constraints/gp.py", line 112, in __init__
    + boundstrs)
ValueError: Geometric Program is not fully bounded:
  C_f has no upper bound
```
I can't explain why this occurs. All I know is that it is aggravating, and I will follow up here about the progress.

**Comment by 1ozturkbe** [comment]
Oops, maybe it is the fact that I am still working on the python3 branch... let me merge master and follow up.

**Comment by bqpd** [comment]
closing until it occurs again
