### ISSUE TITLE
Error installing on WSL: Ubuntu-18.04

### ISSUE THREAD

**Issue by awadell1** [convexengineering/gpkit#1448]
Commands I ran:
```
pip install gpkit
python
from gpkit import Model, Variable, Vectorize
```

Error Message
```
Found` no installed solvers, beginning a build.
# Moving to the directory from which GPkit was imported.
Started building gpkit...

Attempting to find and build solvers:

# Looking for mosek
# the expected MOSEK directory of /home/alex/mosek was not found
# Did not find mosek
# Looking for mosek_cli
#   Trying to run mskexpopt...
#     Calling 'mskexpopt'
##
### CALL BEGINS
/bin/sh: 1: mskexpopt: not found
### CALL ENDS
##
# Did not find mosek_cli
# Looking for cvxopt
#   Trying to import cvxopt...
# Found cvxopt in Python path
...finished building gpkit.

Found the following solvers: cvxopt
#     Replacing directory env
...........................x[:] <= w
F.................................F....F...................................................................................................
======================================================================
FAIL: test_ast (gpkit.tests.t_vars.TestVarKey)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.6/site-packages/gpkit/tests/t_vars.py", line 74, in test_ast
    self.assertEqual(str(x**3), "x[:]^3")
AssertionError: 'x[:]³' != 'x[:]^3'
- x[:]³
?     ^
+ x[:]^3
?     ^^


======================================================================
FAIL: test_repr (gpkit.tests.t_nomials.TestMonomial)
Simple tests for __repr__, which prints more than str
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.6/site-packages/gpkit/tests/t_nomials.py", line 78, in test_repr
    self.assertEqual(repr(m), 'gpkit.Monomial(5*x^2/y)')
AssertionError: 'gpkit.Monomial(5*x²/y)' != 'gpkit.Monomial(5*x^2/y)'
- gpkit.Monomial(5*x²/y)
?                   ^
+ gpkit.Monomial(5*x^2/y)
?                   ^^


======================================================================
FAIL: test_init (gpkit.tests.t_nomials.TestSignomial)
Test Signomial construction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.6/site-packages/gpkit/tests/t_nomials.py", line 237, in test_init
    self.assertEqual(str(1 - x - y**2 - 1), "1 - x - y^2 - 1")
AssertionError: '1 - x - y² - 1' != '1 - x - y^2 - 1'
- 1 - x - y² - 1
?          ^
+ 1 - x - y^2 - 1
?          ^^


----------------------------------------------------------------------
Ran 166 tests in 1.299s

FAILED (failures=3)

GPkit is now installed with solver(s) ['cvxopt']
To incorporate new solvers at a later date, run `gpkit.build()`.

If any tests didn't pass, please post the output above
(starting from "Found no installed solvers, beginning a build.")
to gpkit@mit.edu or https://github.com/convexengineering/gpkit/issues/new
so we can prevent others from having these errors.

The same goes for any other bugs you encounter with GPkit:
send 'em our way, along with any interesting models, speculative features,
comments, discussions, or clarifications you feel like sharing.

Finally, we hope you find our documentation (https://gpkit.readthedocs.io/)
and engineering-design models (https://github.com/convexengineering/gplibrary/)
to be useful resources for your own applications.
```

**Comment by bqpd** [comment]
Ah, sorry, these are normal (for now) for Python 3. Don't worry about the failures! We'll be switching to only supporting Python 3 this January, at which point this will disappear.
