### ISSUE TITLE
Unknown solver 'mosek' 

### ISSUE THREAD

**Issue by courtin** [convexengineering/gpkit#1494]
After updating to latest gpkit version, mosek no longer seems to be working. My installation is unchanged since previous versions and  the license is still valid. 

Similar error messages happen running models with mosek specified; cvxopt works as expected. 

I'm using Mosek 8 on macOS Mojave 10.14.16. 

```
$ python -c "import gpkit.tests; gpkit.tests.run()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/chriscourtin/dev/gpkit/gpkit/tests/run_tests.py", line 54, in run
    tests = import_tests()
  File "/Users/chriscourtin/dev/gpkit/gpkit/tests/run_tests.py", line 27, in import_tests
    from gpkit.tests import t_model
  File "/Users/chriscourtin/dev/gpkit/gpkit/tests/t_model.py", line 792, in <module>
    setattr(test, "ndig", NDIGS[solver])
KeyError: 'mosek'
```

**Comment by bqpd** [comment]
Because there was no speed difference between the "mosek" and "mosek_cli" interfaces for MOSEK8, we dropped "mosek" support as part of the preparation for MOSEK9; sorry for the confusion!
