### ISSUE TITLE
Missing ipynbsankeywidget from dependencies?

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#1536]
Should setup.py include `ipynbsankeywidgets` as a required package?

```
......................................................................EE.....................................
======================================================================
ERROR: test_performance_modeling_cvxopt (gpkit.tests.t_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/philippe.kirschen/Optimization/gpkit/gpkit/tests/helpers.py", line 55, in test
    testfn(name, import_dict, path)(self)
  File "/Users/philippe.kirschen/Optimization/gpkit/gpkit/tests/helpers.py", line 87, in test
    imported[name] = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/philippe.kirschen/Optimization/gpkit/docs/source/examples/performance_modeling.py", line 247, in <module>
    from gpkit.interactive.sankey import Sankey
  File "/Users/philippe.kirschen/Optimization/gpkit/gpkit/interactive/sankey.py", line 8, in <module>
    from ipysankeywidget import SankeyWidget
ModuleNotFoundError: No module named 'ipysankeywidget'

======================================================================
ERROR: test_performance_modeling_mosek_cli (gpkit.tests.t_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/philippe.kirschen/Optimization/gpkit/gpkit/tests/helpers.py", line 55, in test
    testfn(name, import_dict, path)(self)
  File "/Users/philippe.kirschen/Optimization/gpkit/gpkit/tests/helpers.py", line 87, in test
    imported[name] = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/philippe.kirschen/Optimization/gpkit/docs/source/examples/performance_modeling.py", line 247, in <module>
    from gpkit.interactive.sankey import Sankey
  File "/Users/philippe.kirschen/Optimization/gpkit/gpkit/interactive/sankey.py", line 8, in <module>
    from ipysankeywidget import SankeyWidget
ModuleNotFoundError: No module named 'ipysankeywidget'
```

**Comment by bqpd** [comment]
I'm of two minds about that, because it's a pretty heavy dependency and a
lot of users won't use it!

Guess I could check if it's installed before running those unit
tests...what do you think?

**Comment by pgkirsch** [comment]
Ah yea in that case I think checking installation first would be a decent solution.
