### ISSUE TITLE
Cvxopt gives rank(A) ValueError, mosek_cli makes no sense

### ISSUE THREAD

**Issue by pgkirsch** [convexengineering/gpkit#453]
First of all the code below gives the following error from cvxopt:

``` python
Traceback (most recent call last):
  File "cone_and_floor.py", line 172, in <module>
    m.solve()
  File "/Library/Python/2.7/site-packages/gpkit/model.py", line 206, in solve
    *args, **kwargs)
  File "/Library/Python/2.7/site-packages/gpkit/model.py", line 350, in _solve
    result = solvefn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/gpkit/geometric_program.py", line 137, in solve
    k=self.k, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/gpkit/_cvxopt.py", line 42, in cvxoptimize
    solution = gpsolver(k, F, g)
  File "build/bdist.macosx-10.11-intel/egg/cvxopt/cvxprog.py", line 2161, in gp
  File "build/bdist.macosx-10.11-intel/egg/cvxopt/cvxprog.py", line 1966, in cp
  File "build/bdist.macosx-10.11-intel/egg/cvxopt/cvxprog.py", line 782, in cpl
ValueError: Rank(A) < p or Rank([H(x); A; Df(x); G]) < n
```

Second, mosek_cli solves the GP fine. But, there are two constraints that are commented, and if you uncomment either one or both, mosek_cli returns exit status 152. I cannot understand why it would solve the original code yet have trouble when you uncomment the `xWskin` constraint. There is no pressure on this constraint, but there are a few constraints like that, none of which cause issues. The only other constraint that depends on xWskin is the `xWshell >= ...` constraint below it, but if anything adding a lower bound constraint should help not hurt.

``` python
from gpkit import Variable, Model, SignomialsEnabled, units
import numpy as np

# Variables
#        Acone = Variable('Acone', 'm^2', 'Cone enclosed area')
Afloor = Variable('Afloor', 'm^2', 'Floor area')
Afuse = Variable('Afuse', 'm^2', 'Cross sectional area')
Askin = Variable('Askin', 'm^2', 'Cross sectional area of skin')
dRfuse = Variable('dRfuse', 15*0.0254, 'm', 'Offset of lower fuselage cylinder')
hfloor = Variable('hfloor', 5*0.0254, 'm', 'Floor I-beam height') # Value
#        Ihshell = Variable('Ihshell', 'm^4', 'Bending inertia')
#        Ivshell = Variable('Ivshell', 'm^4', 'Bending inertia')
lfloor = Variable('lfloor', 'm', 'Floor length')
lcone = Variable('lcone', 15*0.3048, 'm', 'Cone length') # added this 
lnose = Variable('lnose', 'm', 'Nose length')
lshell = Variable('lshell',102*0.3048-17*0.3048, 'm', 'Shell length')
Mfloor = Variable('Mfloor', 'N*m', 'Maximum bending moment in floor beams')
Pfloor = Variable('Pfloor', 'N', 'Distributed floor load')
plamcone = Variable('plamcone', 1.3, '-', 'Cone taper ratio + 1')
plamv = Variable('plamv', 2.3, '-', 'Tail taper ratio + 2')
qlamv = Variable('qlamv', 1.3, '-', 'Tail taper ratio + 1')
Qv = Variable('Qv', 'N*m', 'Torsion moment imparted by vertical tail')
#        Rcone = Variable('Rcone', 'm', 'Cone radius')
Rfuse = Variable('Rfuse', 77*0.0254, 'm', 'Fuselage radius')
Sbulk = Variable('Sbulk', 'm^2', 'Bulkhead surface area')
Sfloor = Variable('Sfloor', 'N', 'Maximum shear in floor beams')
sigth = Variable('sigth', 'N/m^2', 'Hoop stress in skin')
sigx = Variable('sigx', 'N/m^2', 'Axial stress in skin')
Snose = Variable('Snose', 'm^2', 'Nose surface area')
taucone = Variable('taucone', 'N/m^2', 'Shear stress in cone')
tcone = Variable('tcone', 'm', 'Cone thickness')
tshell = Variable('tshell', 'm', 'Shell thickness')
tskin = Variable('tskin', 'm', 'Skin thickness')
Vbulk = Variable('Vbulk', 'm^3', 'Bulkhead skin volume')
Vcone = Variable('Vcone', 'm^3', 'Volume of cone skin')
Vcyl = Variable('Vcyl', 'm^3', 'Cylinder skin volume')
Vfloor = Variable('Vfloor', 'm^3', 'Floor volume')
Vnose = Variable('Vnose', 'm^3', 'Nose skin volume')
Wapu = Variable('Wapu', 'N', 'Weight of APU')
Wcone = Variable('Wcone', 'N', 'Weight of cone')
wfloor = Variable('wfloor', 'm', 'Floor width')
Wfloor = Variable('Wfloor', 'N', 'Floor weight')
Wfuse = Variable('Wfuse', 'N', 'Fuselage weight')
Winsul = Variable('Winsul', 'N', 'Weight of insulation material')
Wpadd = Variable('Wpadd', 'N', 'Misc weights (attendants, food, galley, toilets, doors etc.)')
Wpay = Variable('Wpay', 177000, 'N', 'Payload weight') # b737.org.uk
Wseat = Variable('Wseat', 'N', 'Weight of seats')
Wshell = Variable('Wshell', 'N', 'Shell weight')
Wskin = Variable('Wskin', 'N', 'Skin weight')
Wwindow = Variable('Wwindow', 'N', 'Weight of windows')
xapu = Variable('xapu', 120*0.3048, 'm', 'x-location of APU')
xconend = Variable('xconend', 117*0.3048, 'm', 'x-loction of cone end')
xshell1 = Variable('xshell1', 17*0.3048, 'm', 'Start of cylinder section') # value subbed as constraint
xshell2 = Variable('xshell2', 102*0.3048, 'm', 'End of cyinder section')
xVbulk = Variable('xVbulk', 'm^4', 'Volume moment of bulkhead')
xVcyl = Variable('xVcyl', 'm^4', 'Volume moment of cylinder')
xVnose = Variable('xVnose', 'm^4', 'Volume moment of nose')
xWapu = Variable('xWapu', 'N*m', 'Moment of APU')
xWcone = Variable('xWcone', 'N*m', 'Moment of cone')
xWfix = Variable('xWfix', 'N*m', 'Moment of fixed weights')
xWfloor = Variable('xWfloor', 'N*m', 'Moment of floor weight')
xWfuse = Variable('xWfuse', 'N*m', 'Fuselage moment')
xWinsul = Variable('xWinsul', 'N*m', 'Mass moment of insulation material')
xWpadd = Variable('xWpadd', 'N*m', 'Moment of misc weights')
xWseat = Variable('xWseat', 'N*m', 'Moment of seats')
xWshell = Variable('xWshell', 'N*m', 'Mass moment of shell')
xWskin = Variable('xWskin', 'N*m', 'Mass moment of skin')
xWwindow = Variable('xWwindow', 'N*m', 'Mass moment of windows')

# Constants ([TAS] means sourced from TASOPT)

bv = Variable('bv', 7, 'm', 'Vertical tail span')
#        CLvmax = Variable('CLvmax', 2.6, '-', 'Tail max lift coefficient') # [TAS]
dp = Variable('\\Deltap', 76000-24000, 'Pa', 'Pressure difference across fuselage skin')
fapu = Variable('fapu', 0.035, '-', 'APU weight as fraction of payload weight') # [TAS]
ffadd = Variable('ffadd', 0.20, '-', 'Skin proportional added weight of local reinforcmenets') # [TAS]
fframe = Variable('fframe', 0.25, '-', 'Fractional weight of frame')
fpadd = Variable('fpadd', 0.35, '-', 'All other misc weight as fraction of payload weight') # [TAS]
fseat = Variable('fseat', 0.10, '-', 'Seat weight as fraction of payload weight')
fstring = Variable('fstring', 0.35, '-', 'Fraction of stringers?') # [TAS]
g = Variable('g', 9.81, 'm/s^2', 'Gravitational acceleration')
Lvmax = Variable('Lvmax', 35000, 'N', 'Tail max lift')
Nland = Variable('Nland', 6.0,  '-', 'Emergency landing load factor') # [TAS]
#        qNE = Variable('qNE', 'Pa', 'Never exceed dynamic pressure')
rE = Variable('rE', 1.0, '-', 'Ratio of stringer/skin moduli') # [TAS]
rhobend = Variable('rhobend', 2700, 'kg/m^3', 'Stringer density') # [TAS]
rhocone = Variable('rhocone', 2700, 'kg/m^3', 'Density of cone material') # [TAS]
rhofloor = Variable('rhofloor', 2700, 'kg/m^3', 'Density of floor material') # [TAS]
rhoskin = Variable('rhoskin', 2700, 'kg/m^3', 'Skin density') # [TAS]
sigfloor = Variable('sigfloor', 30000/0.000145, 'N/m^2', 'Max allowable cap stress') # [TAS]
sigskin = Variable('sigskin', 15000/0.000145, 'N/m^2', 'Max allowable skin stress') # [TAS]
#        Sv = Variable('Sv', 20, 'm^2', 'Tail reference area')
taufloor = Variable('taufloor', 30000/0.000145, 'N/m^2', 'Max allowable shear web stress') # [TAS]
Wfix = Variable('Wfix', 3000*4.45, 'N', 'Fixed weights (pilots, cockpit seats, instrumentation, navcom)')
Wppfloor = Variable('Wppfloor', 60, 'N/m^2', 'Floor weight/area density') # [TAS]
Wppinsul = Variable('Wppinsul', 22, 'N/m^2', 'Weight/Area density of insulation material') # [TAS]
Wpwindow = Variable('Wpwindow', 145.*3, 'N/m', 'Weight/Length density of windows') # [TAS]
xfix = Variable('xfix', 7*0.3048, 'm', 'x-location of fixed weights')


objective = Wfuse

constraints = [
                # Geometry relations
                lnose == xshell1,

                # Cross section relations
                Askin >= 2*np.pi*Rfuse*tskin + 2*dRfuse*tskin,
                Afuse >= np.pi*Rfuse**2 + 2*Rfuse*dRfuse,
                tshell >= tskin*(1 + rE*fstring*rhoskin/rhobend),

                # Pressure shell loads
                sigx == dp/2*Rfuse/tshell,
                sigth == dp*Rfuse/tskin,
                tskin == dp*Rfuse/sigskin,
                Snose**(8./5) >= (2*np.pi*Rfuse**2)**(8./5) * (1./3 + (2./3)*(lnose/Rfuse)**(8./5)),
                Sbulk == 2*np.pi*Rfuse**2,
                Vcyl == Askin*lshell,
                Vnose == Snose*tskin,
                Vbulk == Sbulk*tskin,
                xVcyl >= 0.5*(xshell1+xshell2)*Vcyl,
                xVnose >= 0.5*(xshell1)*Vnose,
                xVbulk >= (xshell2 + 0.5*dRfuse)*Vbulk,
                Wskin >= rhoskin*g*(Vcyl + Vnose + Vbulk),
#               xWskin >= rhoskin*g*(xVcyl + xVnose + xVbulk),
                Wshell >= Wskin*(1 + fstring + fframe + ffadd),
                xWshell >= xWskin*(1 + fstring + fframe + ffadd),

                # Windows and insulation
                Wwindow == Wpwindow * lshell,
                xWwindow >= 0.5* (xshell1+xshell2)*Wwindow,
                Winsul >= Wppinsul*(1.1*np.pi*Rfuse*lshell + 0.55*(Snose + Sbulk)),
                xWinsul >= 0.5*(xshell1 + xshell2)*Winsul,

                # Payload-proportional weights
                Wapu == Wpay*fapu,
                xWapu == xapu*Wapu,
                Wseat == Wpay*fseat,
                xWseat >= 0.5*(xshell1 + xshell2)*Wseat,
                Wpadd == Wpay*fpadd,
                xWpadd >= 0.5*(xshell1 + xshell2)*Wpadd,         

                # Fixed weight
                xWfix == xfix*Wfix,

                # Floor
                Pfloor >= Nland*(Wpay + Wseat),
                Sfloor == 0.5*Pfloor, # without support
                Mfloor == 0.25*Pfloor*wfloor,
                wfloor == Rfuse,
                Afloor >= 2*Mfloor/(sigfloor*hfloor) + 1.5*Sfloor/taufloor,
                Vfloor >= 2*Rfuse*Afloor,
                lfloor >= lshell + 2*Rfuse,
                Wfloor >= rhofloor*g*Vfloor + 2*wfloor*lfloor*Wppfloor,
                xWfloor >= 0.5*(xshell1 + xshell2)*Wfloor,

                # Tail cone
                Qv == Lvmax*bv*plamv/(3*qlamv), # uses same p, q trick as GP for A/C design
                taucone == sigskin,
                Afuse >= np.pi*Rfuse**2 + 2*Rfuse*dRfuse,
                Qv == 2*Afuse*taucone*tcone, # modified to match TASOPT code
                Vcone*Rfuse*plamcone >= 2*Qv/taucone * lcone,
                Wcone >= rhocone*g*Vcone*(1 + fstring + fframe + ffadd),
                xWcone >= 0.5*(xshell2 + xconend) * Wcone,

                Wfuse >= Wcone + Wfloor + Wpadd + Wapu + Wseat + Wwindow + Winsul + Wshell + Wfix,
#                xWfuse >= xWfix + xWapu + xWpadd + xWseat + xWshell + xWcone + xWwindow + xWinsul + xWfloor,
              ]

m = Model(objective, constraints)

m.solve()
```

**Comment by whoburg** [comment]
Re: the mosek failure, I have seen issues like this in my own models -- tracking this down will be good.

Re: the cvxopt failure, probably related to https://github.com/cvxopt/cvxopt/issues/36?

**Comment by bqpd** [comment]
Similar to #454; useless constraints cause problems :(

**Comment by whoburg** [comment]
Argh, but they shouldn't!  :(  we should try to get a MWE for this class of failures.

**Comment by bqpd** [comment]
I propose building from the one in #454

**Comment by whoburg** [comment]
Sounds good. There are 5 in #454, but you mean the second one, right?

**Comment by bqpd** [comment]
Yup! Just added an intriguing MWE at the end of #454. We could potentially create a new issue around that MWE, and close / refer to all the examples of these failures?

**Comment by whoburg** [comment]
Maybe don't close them, but make the solver problems into a separate milestone? It would be good to know for sure that they are resolved.

The mosek 0.0 failure is surprising enough that I have hope it might someday be solved.
